# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fzl/workspace/git_projects/RenderEngineV0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fzl/workspace/git_projects/RenderEngineV0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/fzl/workspace/git_projects/RenderEngineV0/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzl/workspace/git_projects/RenderEngineV0/CMakeFiles /home/fzl/workspace/git_projects/RenderEngineV0//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzl/workspace/git_projects/RenderEngineV0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Shaders.dir/build.make CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

#=============================================================================
# Target rules for targets named UnknownEngine

# Build rule for target.
UnknownEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnknownEngine
.PHONY : UnknownEngine

# fast build rule for target.
UnknownEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/build
.PHONY : UnknownEngine/fast

#=============================================================================
# Target rules for targets named UNIT_TEST_ECS

# Build rule for target.
UNIT_TEST_ECS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UNIT_TEST_ECS
.PHONY : UNIT_TEST_ECS

# fast build rule for target.
UNIT_TEST_ECS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/build
.PHONY : UNIT_TEST_ECS/fast

#=============================================================================
# Target rules for targets named UNIT_TEST_STRUCTURE

# Build rule for target.
UNIT_TEST_STRUCTURE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UNIT_TEST_STRUCTURE
.PHONY : UNIT_TEST_STRUCTURE

# fast build rule for target.
UNIT_TEST_STRUCTURE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_STRUCTURE.dir/build.make CMakeFiles/UNIT_TEST_STRUCTURE.dir/build
.PHONY : UNIT_TEST_STRUCTURE/fast

#=============================================================================
# Target rules for targets named GLAD

# Build rule for target.
GLAD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GLAD
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	$(MAKE) $(MAKESILENT) -f source/external/GLAD/CMakeFiles/GLAD.dir/build.make source/external/GLAD/CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f source/external/CATCH2/Catch2/src/CMakeFiles/Catch2.dir/build.make source/external/CATCH2/Catch2/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f source/external/CATCH2/Catch2/src/CMakeFiles/Catch2WithMain.dir/build.make source/external/CATCH2/Catch2/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

#=============================================================================
# Target rules for targets named vk-bootstrap

# Build rule for target.
vk-bootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vk-bootstrap
.PHONY : vk-bootstrap

# fast build rule for target.
vk-bootstrap/fast:
	$(MAKE) $(MAKESILENT) -f source/external/VKBOOTSTRAP/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build.make source/external/VKBOOTSTRAP/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build
.PHONY : vk-bootstrap/fast

source/project/UNIT_TESTS/test_ecs.o: source/project/UNIT_TESTS/test_ecs.cpp.o
.PHONY : source/project/UNIT_TESTS/test_ecs.o

# target to build an object file
source/project/UNIT_TESTS/test_ecs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/UNIT_TESTS/test_ecs.cpp.o
.PHONY : source/project/UNIT_TESTS/test_ecs.cpp.o

source/project/UNIT_TESTS/test_ecs.i: source/project/UNIT_TESTS/test_ecs.cpp.i
.PHONY : source/project/UNIT_TESTS/test_ecs.i

# target to preprocess a source file
source/project/UNIT_TESTS/test_ecs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/UNIT_TESTS/test_ecs.cpp.i
.PHONY : source/project/UNIT_TESTS/test_ecs.cpp.i

source/project/UNIT_TESTS/test_ecs.s: source/project/UNIT_TESTS/test_ecs.cpp.s
.PHONY : source/project/UNIT_TESTS/test_ecs.s

# target to generate assembly for a file
source/project/UNIT_TESTS/test_ecs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/UNIT_TESTS/test_ecs.cpp.s
.PHONY : source/project/UNIT_TESTS/test_ecs.cpp.s

source/project/UNIT_TESTS/test_structure.o: source/project/UNIT_TESTS/test_structure.cpp.o
.PHONY : source/project/UNIT_TESTS/test_structure.o

# target to build an object file
source/project/UNIT_TESTS/test_structure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_STRUCTURE.dir/build.make CMakeFiles/UNIT_TEST_STRUCTURE.dir/source/project/UNIT_TESTS/test_structure.cpp.o
.PHONY : source/project/UNIT_TESTS/test_structure.cpp.o

source/project/UNIT_TESTS/test_structure.i: source/project/UNIT_TESTS/test_structure.cpp.i
.PHONY : source/project/UNIT_TESTS/test_structure.i

# target to preprocess a source file
source/project/UNIT_TESTS/test_structure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_STRUCTURE.dir/build.make CMakeFiles/UNIT_TEST_STRUCTURE.dir/source/project/UNIT_TESTS/test_structure.cpp.i
.PHONY : source/project/UNIT_TESTS/test_structure.cpp.i

source/project/UNIT_TESTS/test_structure.s: source/project/UNIT_TESTS/test_structure.cpp.s
.PHONY : source/project/UNIT_TESTS/test_structure.s

# target to generate assembly for a file
source/project/UNIT_TESTS/test_structure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_STRUCTURE.dir/build.make CMakeFiles/UNIT_TEST_STRUCTURE.dir/source/project/UNIT_TESTS/test_structure.cpp.s
.PHONY : source/project/UNIT_TESTS/test_structure.cpp.s

source/project/app/application.o: source/project/app/application.cpp.o
.PHONY : source/project/app/application.o

# target to build an object file
source/project/app/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/application.cpp.o
.PHONY : source/project/app/application.cpp.o

source/project/app/application.i: source/project/app/application.cpp.i
.PHONY : source/project/app/application.i

# target to preprocess a source file
source/project/app/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/application.cpp.i
.PHONY : source/project/app/application.cpp.i

source/project/app/application.s: source/project/app/application.cpp.s
.PHONY : source/project/app/application.s

# target to generate assembly for a file
source/project/app/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/application.cpp.s
.PHONY : source/project/app/application.cpp.s

source/project/app/engine.o: source/project/app/engine.cpp.o
.PHONY : source/project/app/engine.o

# target to build an object file
source/project/app/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/engine.cpp.o
.PHONY : source/project/app/engine.cpp.o

source/project/app/engine.i: source/project/app/engine.cpp.i
.PHONY : source/project/app/engine.i

# target to preprocess a source file
source/project/app/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/engine.cpp.i
.PHONY : source/project/app/engine.cpp.i

source/project/app/engine.s: source/project/app/engine.cpp.s
.PHONY : source/project/app/engine.s

# target to generate assembly for a file
source/project/app/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/engine.cpp.s
.PHONY : source/project/app/engine.cpp.s

source/project/app/getApp.o: source/project/app/getApp.cpp.o
.PHONY : source/project/app/getApp.o

# target to build an object file
source/project/app/getApp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/getApp.cpp.o
.PHONY : source/project/app/getApp.cpp.o

source/project/app/getApp.i: source/project/app/getApp.cpp.i
.PHONY : source/project/app/getApp.i

# target to preprocess a source file
source/project/app/getApp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/getApp.cpp.i
.PHONY : source/project/app/getApp.cpp.i

source/project/app/getApp.s: source/project/app/getApp.cpp.s
.PHONY : source/project/app/getApp.s

# target to generate assembly for a file
source/project/app/getApp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/getApp.cpp.s
.PHONY : source/project/app/getApp.cpp.s

source/project/app/main.o: source/project/app/main.cpp.o
.PHONY : source/project/app/main.o

# target to build an object file
source/project/app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/main.cpp.o
.PHONY : source/project/app/main.cpp.o

source/project/app/main.i: source/project/app/main.cpp.i
.PHONY : source/project/app/main.i

# target to preprocess a source file
source/project/app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/main.cpp.i
.PHONY : source/project/app/main.cpp.i

source/project/app/main.s: source/project/app/main.cpp.s
.PHONY : source/project/app/main.s

# target to generate assembly for a file
source/project/app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/main.cpp.s
.PHONY : source/project/app/main.cpp.s

source/project/app/stringTable.o: source/project/app/stringTable.cpp.o
.PHONY : source/project/app/stringTable.o

# target to build an object file
source/project/app/stringTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/stringTable.cpp.o
.PHONY : source/project/app/stringTable.cpp.o

source/project/app/stringTable.i: source/project/app/stringTable.cpp.i
.PHONY : source/project/app/stringTable.i

# target to preprocess a source file
source/project/app/stringTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/stringTable.cpp.i
.PHONY : source/project/app/stringTable.cpp.i

source/project/app/stringTable.s: source/project/app/stringTable.cpp.s
.PHONY : source/project/app/stringTable.s

# target to generate assembly for a file
source/project/app/stringTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/app/stringTable.cpp.s
.PHONY : source/project/app/stringTable.cpp.s

source/project/asset/assetManager.o: source/project/asset/assetManager.cpp.o
.PHONY : source/project/asset/assetManager.o

# target to build an object file
source/project/asset/assetManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/assetManager.cpp.o
.PHONY : source/project/asset/assetManager.cpp.o

source/project/asset/assetManager.i: source/project/asset/assetManager.cpp.i
.PHONY : source/project/asset/assetManager.i

# target to preprocess a source file
source/project/asset/assetManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/assetManager.cpp.i
.PHONY : source/project/asset/assetManager.cpp.i

source/project/asset/assetManager.s: source/project/asset/assetManager.cpp.s
.PHONY : source/project/asset/assetManager.s

# target to generate assembly for a file
source/project/asset/assetManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/assetManager.cpp.s
.PHONY : source/project/asset/assetManager.cpp.s

source/project/asset/modelLoader.o: source/project/asset/modelLoader.cpp.o
.PHONY : source/project/asset/modelLoader.o

# target to build an object file
source/project/asset/modelLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/modelLoader.cpp.o
.PHONY : source/project/asset/modelLoader.cpp.o

source/project/asset/modelLoader.i: source/project/asset/modelLoader.cpp.i
.PHONY : source/project/asset/modelLoader.i

# target to preprocess a source file
source/project/asset/modelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/modelLoader.cpp.i
.PHONY : source/project/asset/modelLoader.cpp.i

source/project/asset/modelLoader.s: source/project/asset/modelLoader.cpp.s
.PHONY : source/project/asset/modelLoader.s

# target to generate assembly for a file
source/project/asset/modelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/modelLoader.cpp.s
.PHONY : source/project/asset/modelLoader.cpp.s

source/project/asset/textureLoader.o: source/project/asset/textureLoader.cpp.o
.PHONY : source/project/asset/textureLoader.o

# target to build an object file
source/project/asset/textureLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/textureLoader.cpp.o
.PHONY : source/project/asset/textureLoader.cpp.o

source/project/asset/textureLoader.i: source/project/asset/textureLoader.cpp.i
.PHONY : source/project/asset/textureLoader.i

# target to preprocess a source file
source/project/asset/textureLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/textureLoader.cpp.i
.PHONY : source/project/asset/textureLoader.cpp.i

source/project/asset/textureLoader.s: source/project/asset/textureLoader.cpp.s
.PHONY : source/project/asset/textureLoader.s

# target to generate assembly for a file
source/project/asset/textureLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/asset/textureLoader.cpp.s
.PHONY : source/project/asset/textureLoader.cpp.s

source/project/configuration/globalValues.o: source/project/configuration/globalValues.cpp.o
.PHONY : source/project/configuration/globalValues.o

# target to build an object file
source/project/configuration/globalValues.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/configuration/globalValues.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/configuration/globalValues.cpp.o
.PHONY : source/project/configuration/globalValues.cpp.o

source/project/configuration/globalValues.i: source/project/configuration/globalValues.cpp.i
.PHONY : source/project/configuration/globalValues.i

# target to preprocess a source file
source/project/configuration/globalValues.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/configuration/globalValues.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/configuration/globalValues.cpp.i
.PHONY : source/project/configuration/globalValues.cpp.i

source/project/configuration/globalValues.s: source/project/configuration/globalValues.cpp.s
.PHONY : source/project/configuration/globalValues.s

# target to generate assembly for a file
source/project/configuration/globalValues.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/configuration/globalValues.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/configuration/globalValues.cpp.s
.PHONY : source/project/configuration/globalValues.cpp.s

source/project/core/clock.o: source/project/core/clock.cpp.o
.PHONY : source/project/core/clock.o

# target to build an object file
source/project/core/clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/clock.cpp.o
.PHONY : source/project/core/clock.cpp.o

source/project/core/clock.i: source/project/core/clock.cpp.i
.PHONY : source/project/core/clock.i

# target to preprocess a source file
source/project/core/clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/clock.cpp.i
.PHONY : source/project/core/clock.cpp.i

source/project/core/clock.s: source/project/core/clock.cpp.s
.PHONY : source/project/core/clock.s

# target to generate assembly for a file
source/project/core/clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/clock.cpp.s
.PHONY : source/project/core/clock.cpp.s

source/project/core/input.o: source/project/core/input.cpp.o
.PHONY : source/project/core/input.o

# target to build an object file
source/project/core/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/input.cpp.o
.PHONY : source/project/core/input.cpp.o

source/project/core/input.i: source/project/core/input.cpp.i
.PHONY : source/project/core/input.i

# target to preprocess a source file
source/project/core/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/input.cpp.i
.PHONY : source/project/core/input.cpp.i

source/project/core/input.s: source/project/core/input.cpp.s
.PHONY : source/project/core/input.s

# target to generate assembly for a file
source/project/core/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/input.cpp.s
.PHONY : source/project/core/input.cpp.s

source/project/core/math.o: source/project/core/math.cpp.o
.PHONY : source/project/core/math.o

# target to build an object file
source/project/core/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/math.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/core/math.cpp.o
.PHONY : source/project/core/math.cpp.o

source/project/core/math.i: source/project/core/math.cpp.i
.PHONY : source/project/core/math.i

# target to preprocess a source file
source/project/core/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/math.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/core/math.cpp.i
.PHONY : source/project/core/math.cpp.i

source/project/core/math.s: source/project/core/math.cpp.s
.PHONY : source/project/core/math.s

# target to generate assembly for a file
source/project/core/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/core/math.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/core/math.cpp.s
.PHONY : source/project/core/math.cpp.s

source/project/debug/log.o: source/project/debug/log.cpp.o
.PHONY : source/project/debug/log.o

# target to build an object file
source/project/debug/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/debug/log.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/debug/log.cpp.o
.PHONY : source/project/debug/log.cpp.o

source/project/debug/log.i: source/project/debug/log.cpp.i
.PHONY : source/project/debug/log.i

# target to preprocess a source file
source/project/debug/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/debug/log.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/debug/log.cpp.i
.PHONY : source/project/debug/log.cpp.i

source/project/debug/log.s: source/project/debug/log.cpp.s
.PHONY : source/project/debug/log.s

# target to generate assembly for a file
source/project/debug/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/debug/log.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/debug/log.cpp.s
.PHONY : source/project/debug/log.cpp.s

source/project/ecs/ecs.o: source/project/ecs/ecs.cpp.o
.PHONY : source/project/ecs/ecs.o

# target to build an object file
source/project/ecs/ecs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/ecs/ecs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/ecs/ecs.cpp.o
.PHONY : source/project/ecs/ecs.cpp.o

source/project/ecs/ecs.i: source/project/ecs/ecs.cpp.i
.PHONY : source/project/ecs/ecs.i

# target to preprocess a source file
source/project/ecs/ecs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/ecs/ecs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/ecs/ecs.cpp.i
.PHONY : source/project/ecs/ecs.cpp.i

source/project/ecs/ecs.s: source/project/ecs/ecs.cpp.s
.PHONY : source/project/ecs/ecs.s

# target to generate assembly for a file
source/project/ecs/ecs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/ecs/ecs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/ecs/ecs.cpp.s
.PHONY : source/project/ecs/ecs.cpp.s

source/project/framework/framework.o: source/project/framework/framework.cpp.o
.PHONY : source/project/framework/framework.o

# target to build an object file
source/project/framework/framework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/framework/framework.cpp.o
.PHONY : source/project/framework/framework.cpp.o

source/project/framework/framework.i: source/project/framework/framework.cpp.i
.PHONY : source/project/framework/framework.i

# target to preprocess a source file
source/project/framework/framework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/framework/framework.cpp.i
.PHONY : source/project/framework/framework.cpp.i

source/project/framework/framework.s: source/project/framework/framework.cpp.s
.PHONY : source/project/framework/framework.s

# target to generate assembly for a file
source/project/framework/framework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/framework/framework.cpp.s
.PHONY : source/project/framework/framework.cpp.s

source/project/memory/allocator.o: source/project/memory/allocator.cpp.o
.PHONY : source/project/memory/allocator.o

# target to build an object file
source/project/memory/allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/memory/allocator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/memory/allocator.cpp.o
.PHONY : source/project/memory/allocator.cpp.o

source/project/memory/allocator.i: source/project/memory/allocator.cpp.i
.PHONY : source/project/memory/allocator.i

# target to preprocess a source file
source/project/memory/allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/memory/allocator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/memory/allocator.cpp.i
.PHONY : source/project/memory/allocator.cpp.i

source/project/memory/allocator.s: source/project/memory/allocator.cpp.s
.PHONY : source/project/memory/allocator.s

# target to generate assembly for a file
source/project/memory/allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/memory/allocator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UNIT_TEST_ECS.dir/build.make CMakeFiles/UNIT_TEST_ECS.dir/source/project/memory/allocator.cpp.s
.PHONY : source/project/memory/allocator.cpp.s

source/project/renderer/renderSystem/renderSystem.o: source/project/renderer/renderSystem/renderSystem.cpp.o
.PHONY : source/project/renderer/renderSystem/renderSystem.o

# target to build an object file
source/project/renderer/renderSystem/renderSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderSystem/renderSystem.cpp.o
.PHONY : source/project/renderer/renderSystem/renderSystem.cpp.o

source/project/renderer/renderSystem/renderSystem.i: source/project/renderer/renderSystem/renderSystem.cpp.i
.PHONY : source/project/renderer/renderSystem/renderSystem.i

# target to preprocess a source file
source/project/renderer/renderSystem/renderSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderSystem/renderSystem.cpp.i
.PHONY : source/project/renderer/renderSystem/renderSystem.cpp.i

source/project/renderer/renderSystem/renderSystem.s: source/project/renderer/renderSystem/renderSystem.cpp.s
.PHONY : source/project/renderer/renderSystem/renderSystem.s

# target to generate assembly for a file
source/project/renderer/renderSystem/renderSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderSystem/renderSystem.cpp.s
.PHONY : source/project/renderer/renderSystem/renderSystem.cpp.s

source/project/renderer/renderer.o: source/project/renderer/renderer.cpp.o
.PHONY : source/project/renderer/renderer.o

# target to build an object file
source/project/renderer/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderer.cpp.o
.PHONY : source/project/renderer/renderer.cpp.o

source/project/renderer/renderer.i: source/project/renderer/renderer.cpp.i
.PHONY : source/project/renderer/renderer.i

# target to preprocess a source file
source/project/renderer/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderer.cpp.i
.PHONY : source/project/renderer/renderer.cpp.i

source/project/renderer/renderer.s: source/project/renderer/renderer.cpp.s
.PHONY : source/project/renderer/renderer.s

# target to generate assembly for a file
source/project/renderer/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/renderer.cpp.s
.PHONY : source/project/renderer/renderer.cpp.s

source/project/renderer/rendererHandles.o: source/project/renderer/rendererHandles.cpp.o
.PHONY : source/project/renderer/rendererHandles.o

# target to build an object file
source/project/renderer/rendererHandles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/rendererHandles.cpp.o
.PHONY : source/project/renderer/rendererHandles.cpp.o

source/project/renderer/rendererHandles.i: source/project/renderer/rendererHandles.cpp.i
.PHONY : source/project/renderer/rendererHandles.i

# target to preprocess a source file
source/project/renderer/rendererHandles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/rendererHandles.cpp.i
.PHONY : source/project/renderer/rendererHandles.cpp.i

source/project/renderer/rendererHandles.s: source/project/renderer/rendererHandles.cpp.s
.PHONY : source/project/renderer/rendererHandles.s

# target to generate assembly for a file
source/project/renderer/rendererHandles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/rendererHandles.cpp.s
.PHONY : source/project/renderer/rendererHandles.cpp.s

source/project/renderer/vulkan/vkCore.o: source/project/renderer/vulkan/vkCore.cpp.o
.PHONY : source/project/renderer/vulkan/vkCore.o

# target to build an object file
source/project/renderer/vulkan/vkCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkCore.cpp.o
.PHONY : source/project/renderer/vulkan/vkCore.cpp.o

source/project/renderer/vulkan/vkCore.i: source/project/renderer/vulkan/vkCore.cpp.i
.PHONY : source/project/renderer/vulkan/vkCore.i

# target to preprocess a source file
source/project/renderer/vulkan/vkCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkCore.cpp.i
.PHONY : source/project/renderer/vulkan/vkCore.cpp.i

source/project/renderer/vulkan/vkCore.s: source/project/renderer/vulkan/vkCore.cpp.s
.PHONY : source/project/renderer/vulkan/vkCore.s

# target to generate assembly for a file
source/project/renderer/vulkan/vkCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkCore.cpp.s
.PHONY : source/project/renderer/vulkan/vkCore.cpp.s

source/project/renderer/vulkan/vkDescriptor.o: source/project/renderer/vulkan/vkDescriptor.cpp.o
.PHONY : source/project/renderer/vulkan/vkDescriptor.o

# target to build an object file
source/project/renderer/vulkan/vkDescriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkDescriptor.cpp.o
.PHONY : source/project/renderer/vulkan/vkDescriptor.cpp.o

source/project/renderer/vulkan/vkDescriptor.i: source/project/renderer/vulkan/vkDescriptor.cpp.i
.PHONY : source/project/renderer/vulkan/vkDescriptor.i

# target to preprocess a source file
source/project/renderer/vulkan/vkDescriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkDescriptor.cpp.i
.PHONY : source/project/renderer/vulkan/vkDescriptor.cpp.i

source/project/renderer/vulkan/vkDescriptor.s: source/project/renderer/vulkan/vkDescriptor.cpp.s
.PHONY : source/project/renderer/vulkan/vkDescriptor.s

# target to generate assembly for a file
source/project/renderer/vulkan/vkDescriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkDescriptor.cpp.s
.PHONY : source/project/renderer/vulkan/vkDescriptor.cpp.s

source/project/renderer/vulkan/vkInitializer.o: source/project/renderer/vulkan/vkInitializer.cpp.o
.PHONY : source/project/renderer/vulkan/vkInitializer.o

# target to build an object file
source/project/renderer/vulkan/vkInitializer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkInitializer.cpp.o
.PHONY : source/project/renderer/vulkan/vkInitializer.cpp.o

source/project/renderer/vulkan/vkInitializer.i: source/project/renderer/vulkan/vkInitializer.cpp.i
.PHONY : source/project/renderer/vulkan/vkInitializer.i

# target to preprocess a source file
source/project/renderer/vulkan/vkInitializer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkInitializer.cpp.i
.PHONY : source/project/renderer/vulkan/vkInitializer.cpp.i

source/project/renderer/vulkan/vkInitializer.s: source/project/renderer/vulkan/vkInitializer.cpp.s
.PHONY : source/project/renderer/vulkan/vkInitializer.s

# target to generate assembly for a file
source/project/renderer/vulkan/vkInitializer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkInitializer.cpp.s
.PHONY : source/project/renderer/vulkan/vkInitializer.cpp.s

source/project/renderer/vulkan/vkUtils.o: source/project/renderer/vulkan/vkUtils.cpp.o
.PHONY : source/project/renderer/vulkan/vkUtils.o

# target to build an object file
source/project/renderer/vulkan/vkUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkUtils.cpp.o
.PHONY : source/project/renderer/vulkan/vkUtils.cpp.o

source/project/renderer/vulkan/vkUtils.i: source/project/renderer/vulkan/vkUtils.cpp.i
.PHONY : source/project/renderer/vulkan/vkUtils.i

# target to preprocess a source file
source/project/renderer/vulkan/vkUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkUtils.cpp.i
.PHONY : source/project/renderer/vulkan/vkUtils.cpp.i

source/project/renderer/vulkan/vkUtils.s: source/project/renderer/vulkan/vkUtils.cpp.s
.PHONY : source/project/renderer/vulkan/vkUtils.s

# target to generate assembly for a file
source/project/renderer/vulkan/vkUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/renderer/vulkan/vkUtils.cpp.s
.PHONY : source/project/renderer/vulkan/vkUtils.cpp.s

source/project/world/scene.o: source/project/world/scene.cpp.o
.PHONY : source/project/world/scene.o

# target to build an object file
source/project/world/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/scene.cpp.o
.PHONY : source/project/world/scene.cpp.o

source/project/world/scene.i: source/project/world/scene.cpp.i
.PHONY : source/project/world/scene.i

# target to preprocess a source file
source/project/world/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/scene.cpp.i
.PHONY : source/project/world/scene.cpp.i

source/project/world/scene.s: source/project/world/scene.cpp.s
.PHONY : source/project/world/scene.s

# target to generate assembly for a file
source/project/world/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/scene.cpp.s
.PHONY : source/project/world/scene.cpp.s

source/project/world/world.o: source/project/world/world.cpp.o
.PHONY : source/project/world/world.o

# target to build an object file
source/project/world/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/world.cpp.o
.PHONY : source/project/world/world.cpp.o

source/project/world/world.i: source/project/world/world.cpp.i
.PHONY : source/project/world/world.i

# target to preprocess a source file
source/project/world/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/world.cpp.i
.PHONY : source/project/world/world.cpp.i

source/project/world/world.s: source/project/world/world.cpp.s
.PHONY : source/project/world/world.s

# target to generate assembly for a file
source/project/world/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnknownEngine.dir/build.make CMakeFiles/UnknownEngine.dir/source/project/world/world.cpp.s
.PHONY : source/project/world/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Shaders"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... GLAD"
	@echo "... UNIT_TEST_ECS"
	@echo "... UNIT_TEST_STRUCTURE"
	@echo "... UnknownEngine"
	@echo "... vk-bootstrap"
	@echo "... source/project/UNIT_TESTS/test_ecs.o"
	@echo "... source/project/UNIT_TESTS/test_ecs.i"
	@echo "... source/project/UNIT_TESTS/test_ecs.s"
	@echo "... source/project/UNIT_TESTS/test_structure.o"
	@echo "... source/project/UNIT_TESTS/test_structure.i"
	@echo "... source/project/UNIT_TESTS/test_structure.s"
	@echo "... source/project/app/application.o"
	@echo "... source/project/app/application.i"
	@echo "... source/project/app/application.s"
	@echo "... source/project/app/engine.o"
	@echo "... source/project/app/engine.i"
	@echo "... source/project/app/engine.s"
	@echo "... source/project/app/getApp.o"
	@echo "... source/project/app/getApp.i"
	@echo "... source/project/app/getApp.s"
	@echo "... source/project/app/main.o"
	@echo "... source/project/app/main.i"
	@echo "... source/project/app/main.s"
	@echo "... source/project/app/stringTable.o"
	@echo "... source/project/app/stringTable.i"
	@echo "... source/project/app/stringTable.s"
	@echo "... source/project/asset/assetManager.o"
	@echo "... source/project/asset/assetManager.i"
	@echo "... source/project/asset/assetManager.s"
	@echo "... source/project/asset/modelLoader.o"
	@echo "... source/project/asset/modelLoader.i"
	@echo "... source/project/asset/modelLoader.s"
	@echo "... source/project/asset/textureLoader.o"
	@echo "... source/project/asset/textureLoader.i"
	@echo "... source/project/asset/textureLoader.s"
	@echo "... source/project/configuration/globalValues.o"
	@echo "... source/project/configuration/globalValues.i"
	@echo "... source/project/configuration/globalValues.s"
	@echo "... source/project/core/clock.o"
	@echo "... source/project/core/clock.i"
	@echo "... source/project/core/clock.s"
	@echo "... source/project/core/input.o"
	@echo "... source/project/core/input.i"
	@echo "... source/project/core/input.s"
	@echo "... source/project/core/math.o"
	@echo "... source/project/core/math.i"
	@echo "... source/project/core/math.s"
	@echo "... source/project/debug/log.o"
	@echo "... source/project/debug/log.i"
	@echo "... source/project/debug/log.s"
	@echo "... source/project/ecs/ecs.o"
	@echo "... source/project/ecs/ecs.i"
	@echo "... source/project/ecs/ecs.s"
	@echo "... source/project/framework/framework.o"
	@echo "... source/project/framework/framework.i"
	@echo "... source/project/framework/framework.s"
	@echo "... source/project/memory/allocator.o"
	@echo "... source/project/memory/allocator.i"
	@echo "... source/project/memory/allocator.s"
	@echo "... source/project/renderer/renderSystem/renderSystem.o"
	@echo "... source/project/renderer/renderSystem/renderSystem.i"
	@echo "... source/project/renderer/renderSystem/renderSystem.s"
	@echo "... source/project/renderer/renderer.o"
	@echo "... source/project/renderer/renderer.i"
	@echo "... source/project/renderer/renderer.s"
	@echo "... source/project/renderer/rendererHandles.o"
	@echo "... source/project/renderer/rendererHandles.i"
	@echo "... source/project/renderer/rendererHandles.s"
	@echo "... source/project/renderer/vulkan/vkCore.o"
	@echo "... source/project/renderer/vulkan/vkCore.i"
	@echo "... source/project/renderer/vulkan/vkCore.s"
	@echo "... source/project/renderer/vulkan/vkDescriptor.o"
	@echo "... source/project/renderer/vulkan/vkDescriptor.i"
	@echo "... source/project/renderer/vulkan/vkDescriptor.s"
	@echo "... source/project/renderer/vulkan/vkInitializer.o"
	@echo "... source/project/renderer/vulkan/vkInitializer.i"
	@echo "... source/project/renderer/vulkan/vkInitializer.s"
	@echo "... source/project/renderer/vulkan/vkUtils.o"
	@echo "... source/project/renderer/vulkan/vkUtils.i"
	@echo "... source/project/renderer/vulkan/vkUtils.s"
	@echo "... source/project/world/scene.o"
	@echo "... source/project/world/scene.i"
	@echo "... source/project/world/scene.s"
	@echo "... source/project/world/world.o"
	@echo "... source/project/world/world.i"
	@echo "... source/project/world/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

